# Generated by Django 5.1 on 2025-12-09 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0003_dogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='dogs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_dog', to='fundraisers.dogs'),
        ),
    ]
